### ISSUE TITLE
subscribe to end of a call

### ISSUE THREAD

**Issue by dummys** [jeansch/py-asterisk#10]
Hi,
I'm trying to use your API to trigger some action when a call is finish, like merge the monitored up/down called audio. I'have successfully implemented the callback on the NewState -> Up for incoming call but I can't make it work for end of call. Can you help me or provide me a example please ?
I tried with subscribing to event like Leave, hangup, parkedcall...
thanks a lot.

**Comment by mouseratti** [comment]
Hello.
This code is very ugly, but it works for me.

```
def main():
 
   def hangup_handler(ami, event):
        dialstatus = event['DialStatus']
        if dialstatus in ('BUSY', ):
            channel = event['Channel']
            channel.Hangup()
        return

    logger.debug('O__0 main function was started  ;-)')
    while True:
        try:
            ami_listener, ami_handler = get_ami(), get_ami()
            ami_listener.events.subscribe('DialEnd', hangup_handler)
            break
        except Exception:
            logger.error(traceback.format_exc())
            sleep(5)

    while True:
        try:
            ami_listener.serve_forever()
        except Exception:
            logger.error(traceback.format_exc())
            ami_listener._connect(), ami_handler._connect()
            sleep(5)
if __name__ == '__main__':
    main()
```

I use 2 connections to the AMI. Listener catches events and calls a handler. 
I think you need to handle an action 'Hangup'

**Comment by dummys** [comment]
thanks for your snippet. When I try to catch "Hangup" nothing happened. Did you know if there is a way to print all received event ?
