### ISSUE TITLE
Permission denied init issue

### ISSUE THREAD

**Issue by idncom** [jeansch/py-asterisk#15]
I am using this module through another extension and originally filed an issue for that project here:
https://github.com/OCA/connector-telephony/issues/81#issuecomment-189502556

Upon further investigation I found that it was actually in this file:
line 407 of /usr/local/lib/python2.7/dist-packages/Asterisk/Manager.py

The PermissionDenied function needs a parameter I believe.

**Comment by jeansch** [comment]
Hello, I'm not able to reproduce:
PermissionDenied is a class, and is used properly

>>> from Asterisk import Manager
>>> raise Manager.PermissionDenied("plop")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Asterisk.Manager.PermissionDenied: Asterisk: plop
