### ISSUE TITLE
SSL support for astmanproxy

### ISSUE THREAD

**Issue by webgourou** [jeansch/py-asterisk#17]
Hello,

does an ssl support will be provided in the future to connect throught a proxy such as astmanproxy ?

Thanks

Aurel

**Comment by jeansch** [comment]
Hello, I might add some code to let use a "custom" socket. So after creating that socket with the SSL library, you'll be able to give it to py-asterisk.

Is that an acceptable solution ?

**Comment by jeansch** [comment]
No answer, I close.
