### ISSUE TITLE
Commit #24 was reverted and is giving error during connection

### ISSUE THREAD

**Issue by cmsalmeida** [jeansch/py-asterisk#32]
Commit #24 was reverted and is giving error during connection
With python3 #24 is correct
Release 0.5.16 gives error, authenticationg, 0.5.15 is ok

**Comment by jeansch** [comment]
Hi,

  Please send me your use-case.
It's not py-asterisk's job to handle encoding, I suggest you to do that in your application.

Jean

**Comment by cmsalmeida** [comment]
Hi,
I'm using py-asterisk in this Odoo module https://github.com/OCA/connector-telephony/pull/156
But I have to freeze py-asterisk to version 0.5.15, because someone removed that enconding from py-asterisk. So 0.5.15 works well, and earlier versions don't work anymore.
Let me know if this is enaugh, and of any help.
Thank you in advance

**Comment by jeansch** [comment]
Reverted the revert.
