### ISSUE TITLE
QueuePause action impossible to unpause

### ISSUE THREAD

**Issue by Briareos12** [jeansch/py-asterisk#36]
Hello, 

You need to remove 'and 'true' or 'false'' like below to allow unpause action : 
   ```
def QueuePause(self, queue, interface, paused):
        'Pause <interface> in <queue>.'

        id = self._write_action('QueuePause', {
            'Queue': queue,
            'Interface': interface,
            'Paused': paused 
        })
```

**Comment by jeansch** [comment]
Hi,

  Why ? Don't you enjoy to use a python boolean ?

Jean

Le lundi 01 juillet 2019 à 08:06 -0700, Briareos12 a écrit :
> Hello,
> You need to remove 'and 'true' or 'false'' like below to allow
> unpause action :
> def QueuePause(self, queue, interface, paused):
>      'Pause <interface> in <queue>.'
> 
>      id = self._write_action('QueuePause', {
>          'Queue': queue,
>          'Interface': interface,
>          'Paused': paused 
>      })

-- 
Jean Schurger <jean@ubity.com> | http://schurger.org
GPG: 21D0 4702 758D 5656 C0D6 3288 1609 9E15 596A E928

**Comment by Briareos12** [comment]
Hi,
Aha I am using boolean var but it's not working in this case. When I passed 'false' to unpause the agent, it does nothing but 'true' works fine. After removing this condition all works fine :)

**Comment by jeansch** [comment]
In Python, both 'false' and 'true' are True.
You want to use False or True


Le mar. 2 juill. 2019 11 h 03, Briareos12 <notifications@github.com> a
écrit :

**Comment by Briareos12** [comment]
I'v quote boolean in my text but my test was with True and False :)

**Comment by jeansch** [comment]
I'closing this issue. Reviewed the code, and it work as expected.
