### ISSUE TITLE
Asterisk Call Manager 2.8.0

### ISSUE THREAD

**Issue by cmutz** [jeansch/py-asterisk#7]
Since update Asterisk 13.5 asterisk_click2dial connector reported a failure in py-Asterisk.

Here is the error message: banner incorrect; got 'Asterisk Call Manager/2.8.0\r\n', expe
cted one of ['Asterisk Call Manager/1.0\r\n', 'Asterisk Call Manager/1.1\r\n', 'Asterisk Call Manager/1.2\r\n', 'Asterisk Call Manager/1.3\r\n']

The banners need to be updated to support Asterisk 13.5 I think.

Thanks,

**Comment by jeansch** [comment]
Hi, you might update your copy of py-asterisk, only the 'Asterisk Call Manager' is checked in the banner now.
